using System;
using System.Collections.Generic;
using System.Text;

using RhuEngine.DataStructure;
using RhuEngine.Datatypes;

using RNumerics;

namespace RhuEngine.WorldObjects
{
	public static class TypeCollections
	{
		public static Type[] StandaredTypes = new[] {
			typeof(int),
			typeof(uint),
			typeof(bool),
			typeof(char),
			typeof(string),
			typeof(float),
			typeof(double),
			typeof(string[]),
			typeof(long),
			typeof(ulong),
			typeof(byte),
			typeof(sbyte),
			typeof(short),
			typeof(ushort),
			typeof(decimal),
			typeof(byte[]),
			typeof(Enum),
			typeof(Type),
			typeof(NetPointer),
			typeof(DateTime),
			typeof(Playback),
			typeof(float[]),
			typeof(int[]),
			typeof(Colorb),
			typeof(Colorf),
			typeof(ColorHSV),
			typeof(ColorMap),
			typeof(ColorMap.ColorPoint),
			typeof(AxisAlignedBox2d),
			typeof(AxisAlignedBox2f),
			typeof(AxisAlignedBox2i),
			typeof(AxisAlignedBox3d),
			typeof(AxisAlignedBox3f),
			typeof(AxisAlignedBox3i),
			typeof(Box2d),
			typeof(Box2f),
			typeof(Box3d),
			typeof(Box3f),
			typeof(Frame3f),
			typeof(Index3i),
			typeof(Index2i),
			typeof(Index4i),
			typeof(Interval1d),
			typeof(Interval1i),
			typeof(Line2d),
			typeof(Line2f),
			typeof(Line3d),
			typeof(Line3f),
			typeof(Matrix2d),
			typeof(Matrix2f),
			typeof(Matrix3d),
			typeof(Matrix3f),
			typeof(Plane3d),
			typeof(Plane3f),
			typeof(Quaterniond),
			typeof(Quaternionf),
			typeof(Ray3d),
			typeof(Ray3f),
			typeof(Segment3d),
			typeof(Segment3f),
			typeof(Triangle2d),
			typeof(Triangle2f),
			typeof(Triangle3d),
			typeof(Triangle3f),
			typeof(Vector2b),
			typeof(Vector2d),
			typeof(Vector2f),
			typeof(Vector2i),
			typeof(Vector2l),
			typeof(Vector2u),
			typeof(Vector3b),
			typeof(Vector3d),
			typeof(Vector3f),
			typeof(Vector3i),
			typeof(Vector3u),
			typeof(Vector4b),
			typeof(Vector4d),
			typeof(Vector4f),
			typeof(Vector4i),
			typeof(Vector4u),
			typeof(Vector3dTuple2),
			typeof(Vector3dTuple3),
			typeof(Vector3fTuple3),
			typeof(Vector2dTuple2),
			typeof(Vector2dTuple3),
			typeof(Vector2dTuple4),
			typeof(Circle3d),
			typeof(Cylinder3d),
		};
	}
}
